
spring:
  datasource:
    url: jdbc:mysql://localhost:20000/pickitalki?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

kakao:
  auth-url: "https://kauth.kakao.com/oauth/authorize"
  redirect-uri: "http://ec2-52-79-242-171.ap-northeast-2.compute.amazonaws.com:8080/auth/kakao/callback"
  token-url: "https://kauth.kakao.com/oauth/token"
  user-info-url: "https://kapi.kakao.com/v2/user/me"


jwt:
  secret-key: "pikytalk-secure-connection-key-keep-friends-together!"
  access-expiration-time: 1800000  # 24?? (???)
  refresh-token-expiration : 604800000 # 7?