kakao:
  auth-url: "https://kauth.kakao.com/oauth/authorize"
  client-id: "? ??? ???? ??? ??? ? api key? ?? ???? ?? ?? ?????."
  redirect-uri: "http://localhost:8080/auth/kakao/callback"
  token-url: "https://kauth.kakao.com/oauth/token"
  user-info-url: "https://kapi.kakao.com/v2/user/me"

jwt:
  secret-key: "pikytalk-secure-connection-key-keep-friends-together!"
  expiration-time: 86400000 # 24?? (???)